#define php version for installation
# available php version : 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0
php_version: 7.4
php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-apcu"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-common"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-dev"
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-imap"
  - "php{{ php_version }}-json"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-opcache"
  - "php{{ php_version }}-sqlite3"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-yaml"